name: ci

on:
  push:
    pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake, MSVC)
        run: cmake -S -B build -G "Visual Studio 17 2022" -A x64
      
      - name: Build (Debug)
        run: cmake --build build --config Debug -- -m

      - name: Run tests (ctest)
        run: ctest --test-dir build --config Debug --output-on-failure
        