name: ci

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake, MSVC, Release-only)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build (Release)
        run: cmake --build build --config Release -- -m

      - name: Run tests (ctest)
        run: ctest --test-dir build -C Release --output-on-failure
